package com.santebienetre.model;

import java.time.LocalDate;
import java.util.Objects;

/**
 * Entity class representing a Health & Wellness record.
 * Used for daily mood tracking, stress assessment, and personalized recommendations.
 * 
 * @author Application Santé & Bien-être
 * @version 1.0
 */
public class SanteBienEtre {

    /** Unique identifier */
    private int id;
    
    /** User identifier (foreign key to user table) */
    private int userId;
    
    /** Daily mood (e.g., Très bien, Bien, Moyen, Stressé) */
    private String humeur;
    
    /** Stress/anxiety level (1-10 scale) */
    private int niveauStress;
    
    /** Sleep quality (1-10 scale) */
    private int qualiteSommeil;
    
    /** Nutrition quality description */
    private String nutrition;
    
    /** Physical activity level/type */
    private String activitePhysique;
    
    /** Personal development state/notes */
    private String developpementPersonnel;
    
    /** Personalized recommendations generated by the service */
    private String recommandations;
    
    /** Date of the record */
    private LocalDate dateSuivi;

    // ==================== Constructors ====================

    /** Default constructor */
    public SanteBienEtre() {
        this.dateSuivi = LocalDate.now();
    }

    /**
     * Full constructor for creating a new record (without id).
     * @param userId User identifier
     * @param humeur Daily mood
     * @param niveauStress Stress level (1-10)
     * @param qualiteSommeil Sleep quality (1-10)
     * @param nutrition Nutrition quality
     * @param activitePhysique Physical activity
     * @param developpementPersonnel Personal development notes
     */
    public SanteBienEtre(int userId, String humeur, int niveauStress, int qualiteSommeil,
                         String nutrition, String activitePhysique, String developpementPersonnel) {
        this.userId = userId;
        this.humeur = humeur;
        this.niveauStress = niveauStress;
        this.qualiteSommeil = qualiteSommeil;
        this.nutrition = nutrition;
        this.activitePhysique = activitePhysique;
        this.developpementPersonnel = developpementPersonnel;
        this.dateSuivi = LocalDate.now();
    }

    /**
     * Full constructor including id (for records loaded from database).
     */
    public SanteBienEtre(int id, int userId, String humeur, int niveauStress, int qualiteSommeil,
                         String nutrition, String activitePhysique, String developpementPersonnel,
                         String recommandations, LocalDate dateSuivi) {
        this.id = id;
        this.userId = userId;
        this.humeur = humeur;
        this.niveauStress = niveauStress;
        this.qualiteSommeil = qualiteSommeil;
        this.nutrition = nutrition;
        this.activitePhysique = activitePhysique;
        this.developpementPersonnel = developpementPersonnel;
        this.recommandations = recommandations;
        this.dateSuivi = dateSuivi != null ? dateSuivi : LocalDate.now();
    }

    // ==================== Getters & Setters ====================

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getHumeur() {
        return humeur;
    }

    public void setHumeur(String humeur) {
        this.humeur = humeur;
    }

    public int getNiveauStress() {
        return niveauStress;
    }

    public void setNiveauStress(int niveauStress) {
        this.niveauStress = niveauStress;
    }

    public int getQualiteSommeil() {
        return qualiteSommeil;
    }

    public void setQualiteSommeil(int qualiteSommeil) {
        this.qualiteSommeil = qualiteSommeil;
    }

    public String getNutrition() {
        return nutrition;
    }

    public void setNutrition(String nutrition) {
        this.nutrition = nutrition;
    }

    public String getActivitePhysique() {
        return activitePhysique;
    }

    public void setActivitePhysique(String activitePhysique) {
        this.activitePhysique = activitePhysique;
    }

    public String getDeveloppementPersonnel() {
        return developpementPersonnel;
    }

    public void setDeveloppementPersonnel(String developpementPersonnel) {
        this.developpementPersonnel = developpementPersonnel;
    }

    public String getRecommandations() {
        return recommandations;
    }

    public void setRecommandations(String recommandations) {
        this.recommandations = recommandations;
    }

    public LocalDate getDateSuivi() {
        return dateSuivi;
    }

    public void setDateSuivi(LocalDate dateSuivi) {
        this.dateSuivi = dateSuivi;
    }

    // ==================== Object methods ====================

    @Override
    public String toString() {
        return "SanteBienEtre{" +
                "id=" + id +
                ", userId=" + userId +
                ", humeur='" + humeur + '\'' +
                ", niveauStress=" + niveauStress +
                ", qualiteSommeil=" + qualiteSommeil +
                ", dateSuivi=" + dateSuivi +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SanteBienEtre that = (SanteBienEtre) o;
        return id == that.id;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
}
